import gupta from './assets/gupta.jpg';
import rojek from './assets/rojek.jpg';
import mazur from './assets/mazur.jpg';
import sozanski from './assets/sozanski.png';

export const appDataGe = {
        h1: 'Oncomedica Arztpraxen',
        sections : {
            offer: ['unser Angebot','wie können wir helfen?'],
            about: ['Unser Team', 'lass uns einander kennenlernen'],
            contact: ['Kontakt', 'hier finden sie uns'],
        },
        appointment: 'einen Termin machen',
        'appointment-details': ['das Amt akzeptiert:', 'Anmeldung geöffnet:', 'Telefonnummer:'],
        p: 'Oncomedica ist ein neuer Ort auf der Landkarte von Zgorzelec, der Ärzte zusammenbringt, die sich seit vielen Jahren um die Gesundheit der Patienten kümmern. Wir möchten, dass jeder, der unsere Kliniken aufsucht, umfassende Hilfe und Sicherheit erhält.',
        contact: {
            title: 'ONCOMEDICA Arztpraxen',
            email: 'info@oncomedica.eu',
            street: 'Wyspiańskiego 45c/2 Straße',
            city: '59-900 Zgorzelec',
        },
        details: {
            'chirurgia' : {
                fullName : 'allgemeine und onkologische Chirurgie',
                list: ['Konsultationen auf dem Gebiet der allgemeinen Chirurgie und der onkologischen Chirurgie',
                        'Dermatoskopie - Untersuchung pigmentierter Läsionen und Muttermale mit einem Dermatoskop',
                        'Diagnose und Behandlung von Brustkrankheiten',
                        'Diagnostics and surgical treatment of melanoma and other skin cancers',
                        'Diagnose und chirurgische Behandlung von Melanomen und anderen Hautkrebsarten',
                        'Entfernung von subkutanen Läsionen, Lipomen, Atheromen, Fibromen, Zysten',
                        'eingewachsene Nagelchirurgie',
                        'Behandlung von pilonidalen Haarzysten',
                        'Qualifikation für andere chirurgische Eingriffe'],
                doctor: 'Anil Gupta',
                doctorImg : gupta,
                gabinet: 'Montag bis Freitag',
                recepcja: 'von 15:00 bis 19:00 Uhr',
                tel: '+48 691 493 757',
                link: 'https://www.znanylekarz.pl/anil-kumar-gupta/chirurg-onkolog/zgorzelec',
                about: 'Ich habe mein Medizinstudium im Juli 1992 an der Medizinischen Universität abgeschlossen Schlesische Piasten in Breslau. Dann begann ich meine Spezialisierung in der allgemeinen Chirurgie, die ich am 9. März 1996 abschloss. Während des zweiten Grades in der allgemeinen Chirurgie sammelte ich weiterhin Erfahrungen und Fähigkeiten, um am 24. Januar 2001 den Titel eines Spezialisten zu erhalten. Fünf Jahre später, am 28. Januar 2006, schloss ich meine Spezialisierung auf onkologische Chirurgie ab. Ich glaube, dass die Arbeit eines Arztes eine ständige Weiterentwicklung der Qualifikationen erfordert, um die Gesundheit des Patienten bestmöglich zu schützen. Aus diesem Grund ergänze ich ständig mein Wissen. 2010 absolvierte ich ein Praktikum in der Brustkrebsklinik und Rekonstruktive Chirurgie am Onkologischen Zentrum in Warschau. 2017 habe ich ein Praktikum in der Abteilung für Onkologische Chirurgie des ersten niederschlesischen Onkologiezentrums in Breslau gemacht. 2018 absolvierte ich ein Praktikum in der Abteilung für Onkologische Chirurgie der 2. Brustabteilung der Bruststation in Breslau. Seit 1993 behandle ich in der Abteilung für Allgemeine und Onkologische Chirurgie des Multispecialist Hospital of Johannes Paul II. In Zgorzelec. Ich bin der stellvertretende Leiter dort. Ich bin Angestellter der Klinik für Allgemeinchirurgie und onkologische Chirurgie. Als Teil der Onkologieklinik leite ich seit 3 ​​Jahren eine Klinik zur Prävention und Behandlung von Brustkrebs. Ich sehe Patienten in der Onkologieklinik des Lausitzer Medizinischen Zentrums in Żary. Ich bin auch Vorsitzender des Disability Adjudication Committee in Zgorzelec. Bei der Arbeit beschäftigt er sich mit Beratung und Behandlung im Bereich der allgemeinen Chirurgie und der onkologischen Chirurgie. Ich trete unter anderem auf chirurgische Behandlung von Hernien, gastrointestinalen Neoplasien, Hautmelanomen. Mein Hauptinteresse gilt der Diagnostik und chirurgischen Behandlung von Brustkrankheiten, insbesondere Brustkrebs. Ich mache auch: Diagnose von Hautläsionen, Mammotombiopsie, onkoplastische Chirurgie, Brustrekonstruktion mit Silikonimplantaten und meinem eigenen Gewebe sowie Rekonstruktion der Brustwarzen.',
            },
            'radiologia' : {
                fullName : 'Radiologie',
                list: ['Ultraschalluntersuchung der Bauchhöhle',
                        'Ultraschall der Schilddrüse',
                        'Brustultraschalluntersuchung',
                        'Doppler-Untersuchung (USG) zur Beurteilung des Zustands von Arterien und Venen',
                        'orthopädische Untersuchungen',
                        'Ultraschalluntersuchung der Drüsenperiode',
                        'Ultraschalluntersuchung der Hüften bei Kindern'],
                doctor: 'Maciej Sozański',
                doctorImg : sozanski,
                gabinet: 'Montag und Donnerstag von 14:00 bis 21:00 Uhr',      
                recepcja: 'täglich, rufen wir Sie bei Bedarf zurück',
                tel: '+48 720 833 338',
                link: null,
                about: 'Ich beschäftige mich seit 1994 mit bildgebender Diagnostik. Das Gebiet, das mich in der Radiologie am meisten interessiert, sind Magnetresonanz- und Gefäßuntersuchungen im Ultraschall. Computer sind meine Leidenschaft. Ich versuche, diese beiden Wissensbereiche zu kombinieren und die Diagnose mit der IT zu unterstützen. Ich führe Ultraschalluntersuchungen der Bauchhöhle, der Schilddrüse, der Brüste, der Doppler-Untersuchungen, der orthopädischen und pädiatrischen Untersuchungen (für Magen- und Hüftgelenke) durch.',
            },
            'ortopedia' : {
                fullName : 'Orthopädie',
                list: ['primäre Arthroplastik dieser Gelenke, insbesondere der sogenannten "schwierigen Gelenke" und der Revisionsarthroplastik',
                        'chirurgische Eingriffe an Extremitätengelenken',
                        'Unfallchirurgie der Gliedmaßen und des Beckens',],
                        doctor: 'Andrzej Rojek',
                        doctorImg : rojek,
                        gabinet: 'von Dienstag bis Donnerstag',
                        recepcja: 'von 10:00 bis 12:00 Uhr',
                        tel: '+48 576 681 237',
                        link: null,
                        about: 'Ich bin Allgemeinchirurg und Spezialist für Orthopädie und Traumatologie des Bewegungsapparates. Ich bin 49 Jahre alt und lebe seit 30 Jahren in Niederschlesien. Seit 13 Jahren arbeite ich in der Orthopädie-Abteilung des Krankenhauses. Jana Pawła II in Zgorzelec, die ich seit 6 Jahren leite. Ich habe 1995 meinen Abschluss mit der höchsten Auszeichnung gemacht und dann meinen Beruf in Provinzkrankenhäusern in Jelenia Góra und Wałbrzych gelernt. Ich gab meine akademische Karriere auf und blieb in Breslau, um zum Wohle der Menschen zu arbeiten, was mir große Freude bereitet. Ich habe mehrere Dutzend Aufbaustudiengänge absolviert und an einer ähnlichen Anzahl von Konferenzen und Schulungen teilgenommen, hauptsächlich im Ausland. Das dort erworbene Wissen nutze ich in meiner täglichen Arbeit.',
            },
            'urologia' : {
                fullName : 'Urologie, Onkologie und Chirurgie',
                list: ['endoskopische Operationen',
                        'wichtigsten onkologischen Verfahren',
                        'minimal-invasive laparoskopische Verfahren',],
                        doctor: 'Jarosław Mazur',
                        doctorImg : mazur,
                        gabinet: 'Mittwoch bis 18:00',
                        recepcja: 'täglich',
                        tel: '+48 75 67 14 200',
                        link: 'https://e-rejestracja.mp.pl/Tickets/d1ce38e5-bf27-407b-a7fc-4e20b2e9d653?resourceKind=0',
                        about: 'wird abgeschlossen',
            },
            'kardiologia' : {
                fullName : 'Kardiologie und Innere Medizin',
                list: ['wird abgeschlossen',],
                doctor: 'Anna Jachowicz & Michał Olech',
                doctorImg : null,
                gabinet: 'wird abgeschlossen',
                recepcja: 'Mittwoch bis 16:00 von 19:00 Uhr',
                tel: '+48 787 833 877',
                link: null,
                about: null,
            },
        }
};